# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Dependencies
markdown:           kramdown
# highlighter:        rouge

# kramdown:
#    auto_ids:       true
    
# Permalinks
# permalink:          pretty

# Server
# source:             "."
# destination:        ./_site
port:               9007
baseurl:            "" # the subpath of your site, e.g. /blog
url:                "http://xn--pearol-xwa.ga" # the base hostname & protocol for your site, e.g. http://example.com
# encoding:           UTF-8


# Social
title:              Sitio No Oficial del Club Atlético Peñarol
email:              abuse.ombudsman@gmail.com
description:        "Club Atlético Peñarol: club de fútbol uruguayo. Pensamos que
                    la democratización de la Institución pasa por que la Popular 
                    tome su gobierno."
twitter_username:   AbuseOmbudsman
github_username:    abuseombudsman

# Build settings

theme:              minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  

repo:               "https://github.com/twbs/bootstrap"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
